local ffi = require("ffi")

ffi.cdef[[
typedef struct Vector2 { float x; float y; } Vector2;
typedef struct Vector3 { float x; float y; float z; } Vector3;
typedef struct Vector4 { float x; float y; float z; float w; } Vector4;
typedef struct Matrix { float m0; float m4; float m8; float m12; float m1; float m5; float m9; float m13; float m2; float m6; float m10; float m14; float m3; float m7; float m11; float m15; } Matrix;
typedef struct Color { unsigned char r; unsigned char g; unsigned char b; unsigned char a; } Color;
typedef struct Rectangle { float x; float y; float width; float height; } Rectangle;
typedef struct Image { void * data; int width; int height; int mipmaps; int format; } Image;
typedef struct Texture { unsigned int id; int width; int height; int mipmaps; int format; } Texture;
typedef struct RenderTexture { unsigned int id; Texture texture; Texture depth; } RenderTexture;
typedef struct NPatchInfo { Rectangle source; int left; int top; int right; int bottom; int layout; } NPatchInfo;
typedef struct GlyphInfo { int value; int offsetX; int offsetY; int advanceX; Image image; } GlyphInfo;
typedef struct Font { int baseSize; int glyphCount; int glyphPadding; Texture2D texture; Rectangle * recs; GlyphInfo * glyphs; } Font;
typedef struct Camera3D { Vector3 position; Vector3 target; Vector3 up; float fovy; int projection; } Camera3D;
typedef struct Camera2D { Vector2 offset; Vector2 target; float rotation; float zoom; } Camera2D;
typedef struct Mesh { int vertexCount; int triangleCount; float * vertices; float * texcoords; float * texcoords2; float * normals; float * tangents; unsigned char * colors; unsigned short * indices; int boneCount; unsigned char * boneIndices; float * boneWeights; float * animVertices; float * animNormals; unsigned int vaoId; unsigned int * vboId; } Mesh;
typedef struct Shader { unsigned int id; int * locs; } Shader;
typedef struct MaterialMap { Texture2D texture; Color color; float value; } MaterialMap;
typedef struct Material { Shader shader; MaterialMap * maps; float[4] params; } Material;
typedef struct Transform { Vector3 translation; Quaternion rotation; Vector3 scale; } Transform;
typedef struct BoneInfo { char[32] name; int parent; } BoneInfo;
typedef struct ModelSkeleton { unsigned int boneCount; BoneInfo * bones; ModelAnimPose bindPose; } ModelSkeleton;
typedef struct Model { Matrix transform; int meshCount; int materialCount; Mesh * meshes; Material * materials; int * meshMaterial; ModelSkeleton skeleton; ModelAnimPose currentPose; Matrix * boneMatrices; } Model;
typedef struct ModelAnimation { char[32] name; unsigned int boneCount; int keyframeCount; ModelAnimPose * keyframePoses; } ModelAnimation;
typedef struct Ray { Vector3 position; Vector3 direction; } Ray;
typedef struct RayCollision { bool hit; float distance; Vector3 point; Vector3 normal; } RayCollision;
typedef struct BoundingBox { Vector3 min; Vector3 max; } BoundingBox;
typedef struct Wave { unsigned int frameCount; unsigned int sampleRate; unsigned int sampleSize; unsigned int channels; void * data; } Wave;
typedef struct AudioStream { rAudioBuffer * buffer; rAudioProcessor * processor; unsigned int sampleRate; unsigned int sampleSize; unsigned int channels; } AudioStream;
typedef struct Sound { AudioStream stream; unsigned int frameCount; } Sound;
typedef struct Music { AudioStream stream; unsigned int frameCount; bool looping; int ctxType; void * ctxData; } Music;
typedef struct VrDeviceInfo { int hResolution; int vResolution; float hScreenSize; float vScreenSize; float eyeToScreenDistance; float lensSeparationDistance; float interpupillaryDistance; float[4] lensDistortionValues; float[4] chromaAbCorrection; } VrDeviceInfo;
typedef struct VrStereoConfig { Matrix[2] projection; Matrix[2] viewOffset; float[2] leftLensCenter; float[2] rightLensCenter; float[2] leftScreenCenter; float[2] rightScreenCenter; float[2] scale; float[2] scaleIn; } VrStereoConfig;
typedef struct FilePathList { unsigned int count; char ** paths; } FilePathList;
typedef struct AutomationEvent { unsigned int frame; unsigned int type; int[4] params; } AutomationEvent;
typedef struct AutomationEventList { unsigned int capacity; unsigned int count; AutomationEvent * events; } AutomationEventList;

void DrawPixel(int posX, int posY, Color color);
void DrawPixelV(Vector2 position, Color color);
void DrawLine(int startPosX, int startPosY, int endPosX, int endPosY, Color color);
void DrawLineV(Vector2 startPos, Vector2 endPos, Color color);
void DrawLineEx(Vector2 startPos, Vector2 endPos, float thick, Color color);
void DrawLineStrip(const Vector2 * points, int pointCount, Color color);
void DrawLineBezier(Vector2 startPos, Vector2 endPos, float thick, Color color);
void DrawLineDashed(Vector2 startPos, Vector2 endPos, int dashSize, int spaceSize, Color color);
void DrawTriangle(Vector2 v1, Vector2 v2, Vector2 v3, Color color);
void DrawTriangleGradient(Vector2 v1, Vector2 v2, Vector2 v3, Color c1, Color c2, Color c3);
void DrawTriangleLines(Vector2 v1, Vector2 v2, Vector2 v3, Color color);
void DrawTriangleFan(const Vector2 * points, int pointCount, Color color);
void DrawTriangleStrip(const Vector2 * points, int pointCount, Color color);
void DrawRectangle(int posX, int posY, int width, int height, Color color);
void DrawRectangleV(Vector2 position, Vector2 size, Color color);
void DrawRectangleRec(Rectangle rec, Color color);
void DrawRectanglePro(Rectangle rec, Vector2 origin, float rotation, Color color);
void DrawRectangleGradientV(int posX, int posY, int width, int height, Color top, Color bottom);
void DrawRectangleGradientH(int posX, int posY, int width, int height, Color left, Color right);
void DrawRectangleGradientEx(Rectangle rec, Color col1, Color col2, Color col3, Color col4);
void DrawRectangleLines(int posX, int posY, int width, int height, Color color);
void DrawRectangleLinesEx(Rectangle rec, float thick, Color color);
void DrawRectangleRounded(Rectangle rec, float roundness, int segments, Color color);
void DrawRectangleRoundedLines(Rectangle rec, float roundness, int segments, Color color);
void DrawRectangleRoundedLinesEx(Rectangle rec, float roundness, int segments, float thick, Color color);
void DrawPoly(Vector2 center, int sides, float radius, float rotation, Color color);
void DrawPolyLines(Vector2 center, int sides, float radius, float rotation, Color color);
void DrawPolyLinesEx(Vector2 center, int sides, float radius, float rotation, float thick, Color color);
void DrawCircle(int centerX, int centerY, float radius, Color color);
void DrawCircleV(Vector2 center, float radius, Color color);
void DrawCircleGradient(Vector2 center, float radius, Color inner, Color outer);
void DrawCircleSector(Vector2 center, float radius, float startAngle, float endAngle, int segments, Color color);
void DrawCircleSectorLines(Vector2 center, float radius, float startAngle, float endAngle, int segments, Color color);
void DrawCircleLines(int centerX, int centerY, float radius, Color color);
void DrawCircleLinesV(Vector2 center, float radius, Color color);
void DrawCircleLinesEx(Vector2 center, float radius, float thick, Color color);
void DrawEllipse(int centerX, int centerY, float radiusH, float radiusV, Color color);
void DrawEllipseV(Vector2 center, float radiusH, float radiusV, Color color);
void DrawEllipseLines(int centerX, int centerY, float radiusH, float radiusV, Color color);
void DrawEllipseLinesV(Vector2 center, float radiusH, float radiusV, Color color);
void DrawRing(Vector2 center, float innerRadius, float outerRadius, float startAngle, float endAngle, int segments, Color color);
void DrawRingLines(Vector2 center, float innerRadius, float outerRadius, float startAngle, float endAngle, int segments, Color color);
void DrawSplineLinear(const Vector2 * points, int pointCount, float thick, Color color);
void DrawSplineBasis(const Vector2 * points, int pointCount, float thick, Color color);
void DrawSplineCatmullRom(const Vector2 * points, int pointCount, float thick, Color color);
void DrawSplineBezierQuadratic(const Vector2 * points, int pointCount, float thick, Color color);
void DrawSplineBezierCubic(const Vector2 * points, int pointCount, float thick, Color color);
void DrawSplineSegmentLinear(Vector2 p1, Vector2 p2, float thick, Color color);
void DrawSplineSegmentBasis(Vector2 p1, Vector2 p2, Vector2 p3, Vector2 p4, float thick, Color color);
void DrawSplineSegmentCatmullRom(Vector2 p1, Vector2 p2, Vector2 p3, Vector2 p4, float thick, Color color);
void DrawSplineSegmentBezierQuadratic(Vector2 p1, Vector2 c2, Vector2 p3, float thick, Color color);
void DrawSplineSegmentBezierCubic(Vector2 p1, Vector2 c2, Vector2 c3, Vector2 p4, float thick, Color color);
void DrawTexture(Texture2D texture, int posX, int posY, Color tint);
void DrawTextureV(Texture2D texture, Vector2 position, Color tint);
void DrawTextureEx(Texture2D texture, Vector2 position, float rotation, float scale, Color tint);
void DrawTextureRec(Texture2D texture, Rectangle rec, Vector2 position, Color tint);
void DrawTexturePro(Texture2D texture, Rectangle srcrec, Rectangle dstrec, Vector2 origin, float rotation, Color tint);
void DrawTextureNPatch(Texture2D texture, NPatchInfo nPatchInfo, Rectangle dstrec, Vector2 origin, float rotation, Color tint);
void DrawFPS(int posX, int posY);
void DrawText(const char * text, int posX, int posY, int fontSize, Color color);
void DrawTextEx(Font font, const char * text, Vector2 position, float fontSize, float spacing, Color tint);
void DrawTextPro(Font font, const char * text, Vector2 position, Vector2 origin, float rotation, float fontSize, float spacing, Color tint);
void DrawTextCodepoint(Font font, int codepoint, Vector2 position, float fontSize, Color tint);
void DrawTextCodepoints(Font font, const int * codepoints, int codepointCount, Vector2 position, float fontSize, float spacing, Color tint);
void DrawLine3D(Vector3 startPos, Vector3 endPos, Color color);
void DrawPoint3D(Vector3 position, Color color);
void DrawCircle3D(Vector3 center, float radius, Vector3 rotationAxis, float rotationAngle, Color color);
void DrawTriangle3D(Vector3 v1, Vector3 v2, Vector3 v3, Color color);
void DrawTriangleStrip3D(const Vector3 * points, int pointCount, Color color);
void DrawCube(Vector3 position, float width, float height, float length, Color color);
void DrawCubeV(Vector3 position, Vector3 size, Color color);
void DrawCubeWires(Vector3 position, float width, float height, float length, Color color);
void DrawCubeWiresV(Vector3 position, Vector3 size, Color color);
void DrawSphere(Vector3 centerPos, float radius, Color color);
void DrawSphereEx(Vector3 centerPos, float radius, int rings, int slices, Color color);
void DrawSphereWires(Vector3 centerPos, float radius, int rings, int slices, Color color);
void DrawCylinder(Vector3 position, float radiusTop, float radiusBottom, float height, int sides, Color color);
void DrawCylinderEx(Vector3 startPos, Vector3 endPos, float startRadius, float endRadius, int sides, Color color);
void DrawCylinderWires(Vector3 position, float radiusTop, float radiusBottom, float height, int sides, Color color);
void DrawCylinderWiresEx(Vector3 startPos, Vector3 endPos, float startRadius, float endRadius, int sides, Color color);
void DrawCapsule(Vector3 startPos, Vector3 endPos, float radius, int rings, int slices, Color color);
void DrawCapsuleWires(Vector3 startPos, Vector3 endPos, float radius, int rings, int slices, Color color);
void DrawPlane(Vector3 centerPos, Vector2 size, Color color);
void DrawRay(Ray ray, Color color);
void DrawGrid(int slices, float spacing);
void DrawModel(Model model, Vector3 position, float scale, Color tint);
void DrawModelEx(Model model, Vector3 position, Vector3 rotationAxis, float rotationAngle, Vector3 scale, Color tint);
void DrawModelWires(Model model, Vector3 position, float scale, Color tint);
void DrawModelWiresEx(Model model, Vector3 position, Vector3 rotationAxis, float rotationAngle, Vector3 scale, Color tint);
void DrawBoundingBox(BoundingBox box, Color color);
void DrawBillboard(Camera camera, Texture2D texture, Vector3 position, float scale, Color tint);
void DrawBillboardRec(Camera camera, Texture2D texture, Rectangle rec, Vector3 position, Vector2 size, Color tint);
void DrawBillboardPro(Camera camera, Texture2D texture, Rectangle rec, Vector3 position, Vector3 up, Vector2 size, Vector2 origin, float rotation, Color tint);
void DrawMesh(Mesh mesh, Material material, Matrix transform);
void DrawMeshInstanced(Mesh mesh, Material material, const Matrix * transforms, int instances);
]]
